.PHONY: migrateup migratedown migratestatus migrateforce

migratedown:
	@echo "Rolling back migrations..."
	migrate -path db/migrations -database "{DB_URL}" -verbose down

migrateup:
	@echo "Running migrations..."
	migrate -path db/migrations -database "{DB_URL}" -verbose up

migratestatus:
	@echo "Checking migration status..."
	migrate -path db/migrations -database "{DB_URL}" -verbose status

migrateforce:
	@echo "Forcing migration version to 1..."
	migrate -path db/migrations -database "{DB_URL}" -verbose force 1

run:
	@echo "Starting the application..."
	@go run main.go

test:
	@echo "Running tests..."
	@go test ./...

build:
	@echo "Building the application..."
	@go build -o bin/savegen-api main.go

clean:
	@echo "Cleaning up..."
	@rm -rf bin/
	@go clean 